### ISSUE TITLE
Exposing the OnEviction callback

### ISSUE THREAD

**Issue by frasergraham** [golang/groupcache#55]
Could the OnEviction callback in the lre cache be exposed by groupcache? Is there a reason this isn't exposed that may not be obvious?

**Comment by adg** [comment]
Because it would complicate the API. Why does your program care?

**Comment by frasergraham** [comment]
Keeping the API simple sounds like a valid reason.

I suppose i'm really asking for a way to know if a key is in the cache or not. My end goal was, when making a decision on something, to be able to give more weight to a path that would use the cache. I had thought to do that by tracking the cached items externally but as I type that out now it sounds a bit over the top.

If a method were added to query for existence of a key in the cache without filling it would that also be considered an unnecessary complexity to the API?

**Comment by adg** [comment]
Complex or not, it's racy. That makes it impossible to use correctly. Let's say you test for the presence of a key and find it, but then by the time you actually access the cache the key has expired. What have you gained?

Groupcache is supposed to be an abstraction that removes the need to think about this stuff. If it doesn't fit your use case, then you should take the groupcache code and adapt it so that it does. Adding more features to the API is probably not the right approach, as it is very hard to design a general purpose cache.

**Comment by frasergraham** [comment]
Yeah, the race condition is a problem, but in the case i'm thinking of, where i'm faced with a choice of N otherwise similar paths and I could choose one that's more likely to be in the cache based on the most up to date data then I don't lose much if that information turns out to be stale.

However, you are right. It doesn't fit the intended use of groupcache so it's not a good idea to add thant kind of functionality.

Thanks for taking the time to respond.
